Update README.md - add description
status-im/sticker-market pull request #16
Opened 2024-02-15 16:06 UTC by 3esmit

2024-02-16 07:53 UTC, 0x-r4bbit requested changes
Nice, thank you @3esmit !
I've suggested some minor fixes and formatting.

Maybe you can update the PR accordingly.

2024-02-16 07:53 UTC, 0x-r4bbit commented on README.md
> +- An authorship NFT (StickerType) which is granted to every registered StickerPack in StickerMarket, intended use is to change the deposit address for all StickerPacks sold in StickerMarket.
```suggestion
- An authorship NFT (`StickerType`) which is granted to every registered `StickerPack` in `StickerMarket`, intended use is to change the deposit address for all `StickerPack`s sold in `StickerMarket`.
```

2024-02-16 07:53 UTC, 0x-r4bbit commented on README.md
> +- StickerMarket main contract, which is the minter of two other NFT smart contract addresses, StickerType and StickerPack. It allows users to mint StickerType, which contains a content-hash link, and
```suggestion
- `StickerMarket` main contract, which is the minter of two other NFT smart contract addresses, `StickerType` and `StickerPack`. It allows users to mint `StickerType`, which contains a content-hash link, and other users to mint `StickerPack` referenced to certain `StickerType`s. 
```

2024-02-16 07:53 UTC, 0x-r4bbit commented on README.md
> +- A purchase NFT (StickerPack) referencing a StickerType, which is granted to any account who paid the value defined in the StickerType while it sale was available.
```suggestion
- A purchase NFT (`StickerPack`) referencing a `StickerType`, which is granted to any account who paid the value defined in the `StickerType` while it sale was available. 
```

2024-02-16 07:53 UTC, 0x-r4bbit commented on README.md
> +Therefore, it models an envoirment where artists can publish their packs for sale, that can be used in official Status app, by holders of StickerPack.  Artists can also sell their token, which new ow
```suggestion
Therefore, it models an environment where artists can publish their packs for sale, that can be used in the official Status app, by holders of `StickerPack`.  Artists can also sell their tokens, which new owners could set a new payment address.
```

2024-02-16 17:17 UTC, 3esmit commented
Good improvements. Commited them.

2024-02-19 09:07 UTC, 0x-r4bbit approved these changes

2024-02-19 09:07 UTC, merged

2024-02-19 09:07 UTC, 0x-r4bbit commented
Good job!